# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/FYPN-site/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Fayette Young Professionals Network
email: info@fayetteyoungprofessionals.org
facebook_username: Fayette-Young-Professionals-135125349889727/
twitter_username: youngfayette
address:
  - line: 65 W Main St. Suite 107 
  - line: Uniontown, PA 15401
  # Feel free to add more lines here 
telephone: (123)-456-7890
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown